### PR TITLE
Copy the original Ardan Labs service code.

### PR DESCRIPTION
**Pull request by spetrovic77**
In subsequent changes, we will modify this code to port it to Service Weaver.

The only difference is that we changed the README.md file to point to the original service repository.

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
Can the team give me a day or two before they start. I have a PR I will be merging and it fixes some inconsistencies and adds a new domain for homes. Worse case, I can tell you when the commmit hits master.

**Comment by spetrovic77** [comment]
Thanks Bill, sure can.

I'm actually considering linking from this repo into ardenlabs/service,
rather than copying the code. The changes will be minimal, and it would fix
the fork issues. I was going to start by changing the sales-api and
sales-admin binaries, and the rest of the code stays the same. WDYT?

**Comment by ardan-bkennedy** [comment]
Do you really think you can use all this code with minimal changes?  MAYBE we add a layer to the app layer called weaver

app/weaver/sales-api

Add your app layer code there and use the business and foundation layers. That would be amazing.

If you think this will work, I can give you access to the service repo. No reason to have a separate repo for this.

**Comment by spetrovic77** [comment]
Thanks, Bill.

Let me send you a PR in ardenlabs/service with weaver changes and we can
decide if it makes sense.

My concern would be the makefile in the root directory, tailored toward
weaver. But perhaps we can just add instructions to weaver there?

The foundation code can 100% stay as it is.

-Srdjan

**Comment by ardan-bkennedy** [comment]
Maybe we can create a new makefile for weaver. Maybe in the weaver folder in the app layer to start.

**Comment by spetrovic77** [comment]
I sent the PR <https://github.com/ardanlabs/service/pull/304> to
ardanlabs/service.

**Pull request merged**
